### ISSUE TITLE
Fatal symbol lookup error on PHP 8.1+: gearman.so calling deprecated ZVAL_NEW_ARR() macro.

### ISSUE THREAD

**Issue by trenshaw** [php/pecl-networking-gearman#16] opened 2022-09-15 00:35 UTC
The ZVAL_NEW_ARR() macro has been removed as of PHP 8.1. It is advised to use array_init() or ZVAL_ARR with zend_new_array() instead.

Refer link to internal API changes: https://github.com/php/php-src/blob/PHP-8.1/UPGRADING.INTERNALS

**Comment by trenshaw** [comment] 2022-09-15 00:43
I have version 2.1.0 installed via PECL on Ubuntu 22.04.1. This appears to have been removed already in commit 15 mo. ago by @remicollet was this change pulled into 2.1.0?

**Comment by trenshaw** [comment] 2022-09-21 00:16
I can confirm the 'master' branch currently passes 'make test' and installs against libgearman v1.1.19 and PHP 8.1.2 (the default packages in Ubuntu 22.04). Perhaps 'master' could now be tagged a release candidate for 2.1.1? There will be many other Ubuntu 22.04 users facing the same issue with 2.1.0.

**Comment by andrewmy** [comment] 2023-03-20 13:13
@rlerdorf I see that the issue is already fixed in master, could you please do a new release? Thanks! 🙏

**Comment by igordeveloper** [comment] 2023-05-19 18:26
> @rlerdorf I see that the issue is already fixed in master, could you please do a new release? Thanks! pray

Any news about a new release with PHP 8.2 support?

**Closed** 2024-04-05 06:05 UTC
